# Generated by Django 4.2.3 on 2023-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='cff2a76a0a', max_length=10, unique=True),
        ),
    ]
